version: '3'
services:
  nginx:
    ports:
      - 80:80
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - ${PORT}:3000
    command: npm run start:prod

  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
