version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      PORT: 3000
    depends_on:
      - postgres

  postgres:
    container_name: postgres-database
    image: postgres:10.4
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    ports:
      - 5432:5432

  postgres_admin:
    image: dpage/pgadmin4:5.1
    restart: always
    depends_on:
      - postgres
    env_file:
      - docker.env
    ports:
      - 5050:80
volumes:
  db-data:
